[package]
name    = "oxc_napi_resolver"
version = "0.0.0"
publish = false

[lib]
crate-type = ["cdylib"]
test       = false
doctest    = false

[dependencies]
oxc_resolver = { path = ".." }
napi         = { version = "2.16.6", default-features = false, features = ["napi3", "serde-json"] }
napi-derive  = { version = "2.16.5" }

[build-dependencies]
napi-build = "2.1.3"

[package.metadata.cargo-machete]
ignored = ["napi"]
