[package]
name = "oxc_napi_resolver"
version = "0.0.0"
edition = "2021"
publish = false
rust-version = "1.71"

[lib]
crate-type = ["cdylib"]
test = false
doctest = false

[dependencies]
napi = { version = "3.0.0-alpha", default-features = false, features = ["napi3", "serde-json"] }
napi-derive = { version = "3.0.0-alpha" }
oxc_resolver = { path = ".." }
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["std", "fmt"] } # Omit the `regex` feature

[build-dependencies]
napi-build = "2.1.3"

[package.metadata.cargo-machete]
ignored = ["napi"]
