[package]
name         = "oxc_napi_resolver"
version      = "0.0.0"
publish      = false
edition      = "2021"
rust-version = "1.71"

[lib]
crate-type = ["cdylib"]
test       = false
doctest    = false

[dependencies]
oxc_resolver       = { path = ".." }
napi               = { version = "2.16.7", default-features = false, features = ["napi3", "serde-json", "async"] }
napi-derive        = { version = "2.16.6" }
tokio              = "1.38.0"
tracing-subscriber = { version = "0.3.18", features = [] }                                                         # Omit the `regex` feature

[build-dependencies]
napi-build = "2.1.3"

[package.metadata.cargo-machete]
ignored = ["napi"]
