name: Pnpm

description: Install pnpm

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: pnpm
      shell: bash
      run: |
        corepack enable
        pnpm install

    - name: yarn
      shell: bash
      run: |
        cd fixtures/pnp
        corepack enable
        yarn install
