name: Pnpm

description: Install pnpm

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: yarn
      shell: bash
      run: |
        cd fixtures/pnp
        corepack enable
        yarn install

    - name: pnpm
      shell: bash
      run: |
        corepack enable
        pnpm install
