name: Benchmark

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**/*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1

      - uses: Boshen/setup-rust@main
        with:
          cache-key: benchmark
          save-cache: ${{ github.ref_name == 'main' }}
          tools: cargo-codspeed

      - uses: ./.github/actions/pnpm

      - run: cargo codspeed build --features codspeed
        env:
          RUSTFLAGS: "-C debuginfo=1 -C strip=none"

      - uses: CodSpeedHQ/action@v3
        timeout-minutes: 30
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
