name: Code Coverage # Run cargo-llvm-cov and upload to codecov.io

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**/*.rs"
      - "Cargo.lock"
  push:
    branches:
      - main
    paths:
      - "src/**/*.rs"
      - "Cargo.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1

      - uses: ./.github/actions/pnpm

      - uses: Boshen/setup-rust@main
        with:
          cache-key: codecov
          save-cache: ${{ github.ref_name == 'main' }}
          tools: cargo-llvm-cov
          components: llvm-tools-preview

      - run: cargo llvm-cov --lcov --output-path lcov.info

      - name: Upload Artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: codecov
          path: lcov.info

  # codecov often fails, use another workflow for retry
  upload-codecov:
    name: Upload coverage file
    runs-on: ubuntu-latest
    needs: coverage
    # Check if the event is not triggered by a fork by checking whether CODECOV_TOKEN is set
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout
        if: env.CODECOV_TOKEN
        uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1

      - name: Download coverage file
        if: env.CODECOV_TOKEN
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: codecov

      - name: Upload to codecov.io
        if: env.CODECOV_TOKEN
        uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: lcov.info
