name: Release Plz

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.OXC_BOT_PAT }}

      - uses: Boshen/setup-rust@main
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: warm

      - name: Run release-plz
        id: release-plz
        uses: MarcoIeni/release-plz-action@db75300cf27adcd986d6f0cf4a72a4ffcc11dae5 # v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.OXC_BOT_PAT }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Bump package.json
        if: ${{ steps.release-plz.outputs.prs_created }}
        env:
          GH_TOKEN: ${{ secrets.OXC_BOT_PAT }}
          RELEASES: ${{ steps.release-plz.outputs.releases }}
          PR: ${{ steps.release-plz.outputs.pr }}
        run: |
          set -e

          echo $RELEASES

          pr_number=${{ fromJSON(steps.release-plz.outputs.pr).number }}
          if [[ -n "$pr_number" ]]; then
            version=$(echo "$RELEASES" | jq -r '.[0].version')
            echo "version: $version"

            jq --arg version "${version}" '.version = ($version)' npm/package.json > tmp
            mv tmp npm/package.json

            gh pr checkout $pr_number
            git add .
            git commit --amend --no-edit
            git push --force-with-lease
          fi
